version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 1
  ignore:
  # v0.19.4-v0.19.6 break bot reconnection when moved between voice channels.
  # Remove this once a release later than v0.19.6 is available.
  - dependency-name: github.com/disgoorg/disgo
    versions: ["<= 0.19.6"]

